In [4]:
import os

print(os.listdir())

['.config', 'sample_data']

In [5]:
!find / -name "train.csv"

find: ‘/proc/70/task/70/net’: Invalid argument
find: ‘/proc/70/net’: Invalid argument
/train.csv

In [7]:
import pandas as pd

df = pd.read_csv("/train.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [9]:
print("Rows and Columns:", df.shape)

Rows and Columns: (9800, 18)

In [10]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [11]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [12]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [13]:
print("Average Sales:", df["Sales"].mean())

Average Sales: 230.7690594591837

In [14]:
print("Maximum Sales:", df["Sales"].max())

Maximum Sales: 22638.48

In [15]:
print("Minimum Sales:", df["Sales"].min())

Minimum Sales: 0.444

In [16]:
print("Total Sales:", df["Sales"].sum())

Total Sales: 2261536.7827000003

In [17]:
df.groupby("Region")["Sales"].sum()

Region
Central    492646.9132
East       669518.7260
South      389151.4590
West       710219.6845
Name: Sales, dtype: float64

In [18]:
df.nlargest(5, "Sales")[["Product Name", "Sales"]]

                                           Product Name      Sales
2697  Cisco TelePresence System EX90 Videoconferenci...  22638.480
6826              Canon imageCLASS 2200 Advanced Copier  17499.950
8153              Canon imageCLASS 2200 Advanced Copier  13999.960
2623              Canon imageCLASS 2200 Advanced Copier  11199.968
4190              Canon imageCLASS 2200 Advanced Copier  10499.970

In [19]:
df["Region"].value_counts()

Region
West       3140
East       2785
Central    2277
South      1598
Name: count, dtype: int64

In [20]:
print("Unique Customers:", df["Customer ID"].nunique())

Unique Customers: 793

Question 1:
Natural Language: What is the average sales?
Manual Pandas:
df["Sales"].mean()

Question 2:
Natural Language: Total sales by region
Manual Pandas:
df.groupby("Region")["Sales"].sum()

Question 3:
Natural Language: Top 5 products by sales
Manual Pandas:
df.nlargest(5,"Sales")

In [22]:
try:
    data = pd.read_csv("/train.csv")
    print("Dataset loaded successfully")
except FileNotFoundError:
    print("File not found")
except Exception as e:
    print(e)

Dataset loaded successfully

Note:

PandasAI could not be installed because of a Python compatibility issue in the current environment. Therefore, the required natural language data analysis tasks were completed using standard Pandas.s